---
- hosts: extremetoaster
  sudo: no
  gather_facts: no
  roles:
    - role: bootstrap
    - role: dependencies
    - role: nginx
    - role: et9001
  vars:
    sourcedir: "/Users/chrisgrimmett/scripts/et9001"
    nginx_sites:
      default:
        - listen 80
        - server_name extremetoastesr
        - root "/srv/www/extremetoaster"
        - location / { try_files $uri $uri/ /index.html; }
